spring:
# JPA CONFIG
  jpa:
    properties:
      hibernate:
        "[dialect]": org.hibernate.dialect.MySQL8Dialect
        "[format_sql]": true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

# ===== DATABASE CONFIG =====
    url: jdbc:mysql://localhost:3306/my_app?useSSL=false
    username: root
    password: root

# ===== HIKARICP POOL CONFIG (Tùy chọn để tối ưu hiệu suất) =====
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 2000
      max-lifetime: 1800000
      pool-name: MyHikariCP

  #Setting message properties]
  messages:
    basename: messages

  #Setting Send Mail by Gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanductai.dhv@gmail.com
    password: jtii hajw fwan ktda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  h2:
    console:
      enabled: true

# LOGGIN CONFIG
logging:
  level:
    "[org.springframework.security]": DEBUG

app:
  jwt:
    secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expiration-milliseconds: 300000
    refresh:
      expiration-milliseconds: 600000

open:
  api:
    title: Quiz App
    version: v1.0.0
    description: Create By TaiVD
    serverUrl: http://localhost:8080/
    serverName: Server Test API

management:
  endpoints:
    web:
      exposure:
        include: '*'