server:
  port: 8080
  connection-timeout: 5s
  tomcat:
    keep-alive-timeout: 15s
    max-connections: 200

spring:
  application:
    name: Quiz App
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO